# Generated by Django 6.0.2 on 2026-03-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='academics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(max_length=20)),
                ('department', models.TextField(max_length=20)),
                ('current_level', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='student_record_app',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('State_of_origin', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=15)),
            ],
        ),
    ]
