# Generated by Django 6.0.2 on 2026-03-02 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_record_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='identity',
        ),
    ]
