# Generated by Django 6.0.2 on 2026-03-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_record_app', '0002_delete_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('State_of_origin', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='student_record_app',
        ),
    ]
