# Generated by Django 6.0.2 on 2026-03-05 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_record_app', '0003_student_delete_student_record_app'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='State_of_origin',
            new_name='state_of_origin',
        ),
    ]
